services:
  metricbeat:
    image: ${METRICBEAT_IMAGE}
    container_name: metricbeat
    network_mode: host
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}        
    volumes:
      - ./configs/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./configs/modules.d:/usr/share/metricbeat/modules.d:ro

      # system module
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
